version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    #command: python /code/manage.py runserver 0.0.0.0:8000
    command: uwsgi --http :8000 --wsgi-file inquirer_api/wsgi.py --master --process 4 --threads 2
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: